### PR TITLE
DBError Fix (Invisible Stalker)

### PR DESCRIPTION
**Pull request by ghost**
fixes https://github.com/callmephil/SunWellCore/issues/30

### CODE REVIEW

**Comment by pak3935** [comment]
For me, just working

**Comment by lashia** [comment]
@pak3935 wirh this commit?

**Comment by pak3935** [comment]
@lashia  yes

**Comment by tea91** [comment]
It works perfectly. :+1:

**Comment by callmephil** [comment]
-- accepted. confirm works.

**Pull request merged**
